var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/terms-of-service/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0a9c2f2._.js")
R.c("server/chunks/ssr/node_modules_0vtdjw7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0x~bvoh.js")
R.c("server/chunks/ssr/[root-of-the-server]__1258d~8._.js")
R.c("server/chunks/ssr/[root-of-the-server]__09z7o2x._.js")
R.c("server/chunks/ssr/app_layout_tsx_13yf0ls._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_terms-of-service_page_actions_0oq-ll4.js")
R.m(69858)
module.exports=R.m(69858).exports
