var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/edit-profile/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0sivdn9._.js")
R.c("server/chunks/ssr/node_modules_0vtdjw7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0ior97t.js")
R.c("server/chunks/ssr/[root-of-the-server]__1258d~8._.js")
R.c("server/chunks/ssr/[root-of-the-server]__09z7o2x._.js")
R.c("server/chunks/ssr/app_layout_tsx_13yf0ls._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_edit-profile_page_actions_0mv0v_l.js")
R.m(7954)
module.exports=R.m(7954).exports
